version: '3.9'

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./../data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
    - network

networks:
  network: