version: '3.9'

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      ports: 3306:3306
    networks:
    - network

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:5000
    networks:
      - network
    depends_on: 
    - database

networks:
  network: