version: '3.9'

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./../data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      ports: 3306:3306
    networks:
    - network

  web:
    build: .
    volumes:
      - .:/usr/src/
    environment:
      FLASK_APP: ./__init__.py
    ports:
      - 8001:5000
    networks:
      - network
    depends_on: 
      database:
        condition: service_healthy

networks:
  network: